<?php
/**
 * Implement hook_menu().
 */
function embed_wr_dictionary_menu() {
  $items = array();
  $items['admin/settings/wr-dictionary'] = array(
    'title' => t('Embededded Dictionary'),
    'description' => t('Settings for embedded wordreference dictionary.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('embed_wr_dictionary_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
/**
* Dictionary settings form
* 
* @param mixed $form_state
*/
function embed_wr_dictionary_settings_form($form_state=array()) {
  $dict_options = array(
    "enzh" => "English<>Chinese", 
    "enes" => "English<>Spanish",
    "ende" => "English<>German",
    "enru" => "English<>Russian",
    "enfr" => "English<>French",
    "enit" => "English<>Italian",
    "enpt" => "English<>Portuguese",
    "enpl" => "English<>Polish",
    "enro" => "English<>Romanian",
    "engr" => "English<>Greek",
    "enzh" => "English<>Chinese",
    "enja" => "English<>Japanese",
    "enko" => "English<>Korean",
    "encz" => "English<>Czech",
    "entr" => "English<>Turkish",
  );
  $form['wr_default_dictionary'] = array(
    '#title' => t('Select default dictionary'),
    '#type' => 'select',
    '#options' => $dict_options,
    '#default_value' => variable_get('wr_default_dictionary', 'enzh')
  );
  $form['wr_userid'] = array(
    '#title' => t('WordReference.com Userid'),
    '#type' => 'textfield',
    '#description' => t('You should set your own userid by creating an account at <a href="@link">@link</a> and copying your userid', array('@link' => 'http://forum.wordreference.com/register.php')),
    '#default_value' => variable_get('wr_userid', 1)
  );
  return system_settings_form($form);   
}
/**
* Implementation of hook_block() Dictionary Block
* 
* @param mixed $op
* @param mixed $delta
* @param mixed $edit
*/
function embed_wr_dictionary_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Dictionary'), 
      'cache' => BLOCK_CACHE_PER_ROLE | BLOCK_CACHE_PER_PAGE, 
    );
    return $blocks;
  }
  else if ($op == 'view') {
    switch ($delta) {
      case 0:
        $block = array(
          'subject' => t('Dictionary'), 
          'content' => embed_wr_dictionary_viewblock(),
        );
        break;
    }
    return $block;
  }
}
function embed_wr_dictionary_viewblock() {
  drupal_add_js(drupal_get_path('module', 'embed_wr_dictionary') .'/js/embed_wr_dictionary.js'); 
  $dictionary = variable_get('wr_default_dictionary', 'enzh');
  $userid = variable_get('wr_userid', 1);
  return theme_render_template(drupal_get_path('module', 'embed_wr_dictionary') . '/templates/dictionary_block.tpl.php', array('dictionary' => $dictionary, 'userid' => $userid));
}